spring:
  application:
    name: Hex
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
url:
  random-photo: https://picsum.photos/
  id: 200
  duration-seconds: 5