CREATE SEQUENCE IF NOT EXISTS ORDER_SEQ
    START WITH 1
    INCREMENT BY 25
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE SEQUENCE IF NOT EXISTS OUTBOX_SEQ
    START WITH 1
    INCREMENT BY 25
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;